DELETE FROM tb_subtopics WHERE id_subtopic > 0;
DELETE FROM tb_topics WHERE id_topic > 0;
DELETE FROM tb_topics_types WHERE id_type > 0;
DELETE FROM tb_orders WHERE id_order > 0;
DELETE FROM tb_orders_status WHERE id_status > 0;
DELETE FROM tb_carts_products WHERE id_cart_product > 0;
DELETE FROM tb_carts WHERE id_cart > 0;
DELETE FROM tb_wishlist WHERE id_user > 0 AND id_product > 0;
DELETE FROM tb_products_categories WHERE id_product > 0 AND id_product > 0;
DELETE FROM tb_categories WHERE id_category > 0;
DELETE FROM tb_products WHERE id_product > 0;
DELETE FROM tb_addresses WHERE id_address > 0;
DELETE FROM tb_users_passwords_recoveries WHERE id_recovery > 0;
DELETE FROM tb_mails WHERE id_mail > 0;
DELETE FROM tb_users_logs WHERE id_log > 0;
DELETE FROM tb_users WHERE id_user > 0;
DELETE FROM tb_persons WHERE id_person > 0;
DELETE FROM tb_contacts WHERE id_contact > 0;
DELETE FROM tb_street_types WHERE id_street_type > 0;
DELETE FROM tb_cities WHERE id_city > 0;
DELETE FROM tb_states WHERE id_state > 0;
DELETE FROM tb_countries WHERE id_country > 0;

ALTER TABLE tb_subtopics AUTO_INCREMENT = 1;
ALTER TABLE tb_topics AUTO_INCREMENT = 1;
ALTER TABLE tb_topics_types AUTO_INCREMENT = 1;
ALTER TABLE tb_orders AUTO_INCREMENT = 1;
ALTER TABLE tb_orders_status AUTO_INCREMENT = 1;
ALTER TABLE tb_carts_products AUTO_INCREMENT = 1;
ALTER TABLE tb_carts AUTO_INCREMENT = 1;
ALTER TABLE tb_wishlist AUTO_INCREMENT = 1;
ALTER TABLE tb_products_categories AUTO_INCREMENT = 1;
ALTER TABLE tb_categories AUTO_INCREMENT = 1;
ALTER TABLE tb_products AUTO_INCREMENT = 1;
ALTER TABLE tb_addresses AUTO_INCREMENT = 1;
ALTER TABLE tb_users_passwords_recoveries AUTO_INCREMENT = 1;
ALTER TABLE tb_mails AUTO_INCREMENT = 1;
ALTER TABLE tb_users_logs AUTO_INCREMENT = 1;
ALTER TABLE tb_users AUTO_INCREMENT = 1;
ALTER TABLE tb_persons AUTO_INCREMENT = 1;
ALTER TABLE tb_contacts AUTO_INCREMENT = 1;
ALTER TABLE tb_street_types AUTO_INCREMENT = 1;
ALTER TABLE tb_cities AUTO_INCREMENT = 1;
ALTER TABLE tb_states AUTO_INCREMENT = 1;
ALTER TABLE tb_countries AUTO_INCREMENT = 1;